import type { Contact } from '@/db/schema';

/**
 * Mock contacts for development and testing
 */

export interface MockContact {
  contact: Omit<Contact, 'createdAt' | 'updatedAt' | 'lastContactedAt'> & {
    createdAt: Date;
    updatedAt: Date;
    lastContactedAt: Date | null;
  };
  email: string;
  phone?: string | null;
  tags: string[];
}

export const mockContacts: MockContact[] = [
  {
    contact: {
      id: '1',
      userId: '1',
      firstName: 'Sarah',
      lastName: 'Johnson',
      displayName: 'Sarah Johnson',
      nickname: null,
      company: 'TechCorp Inc.',
      jobTitle: 'Senior Product Manager',
      department: 'Product',
      birthday: new Date('1990-05-15'),
      notes: 'Met at tech conference 2024. Very interested in AI features.',
      avatarUrl: 'https://i.pravatar.cc/150?img=1',
      avatarProvider: null,
      sourceType: 'manual',
      sourceProvider: null,
      sourceId: null,
      isFavorite: true,
      isArchived: false,
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-10-10'),
      lastContactedAt: new Date('2024-10-12'),
    },
    email: 'sarah.johnson@techcorp.com',
    phone: '+1-555-0123',
    tags: ['work', 'important'],
  },
  {
    contact: {
      id: '2',
      userId: '1',
      firstName: 'Michael',
      lastName: 'Chen',
      displayName: 'Michael Chen',
      nickname: 'Mike',
      company: 'StartupXYZ',
      jobTitle: 'CTO',
      department: 'Engineering',
      birthday: null,
      notes: 'Potential collaboration partner',
      avatarUrl: 'https://i.pravatar.cc/150?img=12',
      avatarProvider: null,
      sourceType: 'synced',
      sourceProvider: 'google',
      sourceId: 'google_123',
      isFavorite: true,
      isArchived: false,
      createdAt: new Date('2024-02-20'),
      updatedAt: new Date('2024-10-08'),
      lastContactedAt: new Date('2024-10-08'),
    },
    email: 'michael@startupxyz.io',
    phone: '+1-555-0456',
    tags: ['work', 'startup'],
  },
  {
    contact: {
      id: '3',
      userId: '1',
      firstName: 'Emily',
      lastName: 'Rodriguez',
      displayName: 'Emily Rodriguez',
      nickname: null,
      company: 'Design Studio LLC',
      jobTitle: 'Creative Director',
      department: 'Design',
      birthday: new Date('1988-11-22'),
      notes: null,
      avatarUrl: 'https://i.pravatar.cc/150?img=5',
      avatarProvider: null,
      sourceType: 'manual',
      sourceProvider: null,
      sourceId: null,
      isFavorite: false,
      isArchived: false,
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-09-30'),
      lastContactedAt: new Date('2024-09-28'),
    },
    email: 'emily@designstudio.com',
    phone: '+1-555-0789',
    tags: ['client'],
  },
  {
    contact: {
      id: '4',
      userId: '1',
      firstName: 'David',
      lastName: 'Kumar',
      displayName: 'David Kumar',
      nickname: null,
      company: 'Acme Corporation',
      jobTitle: 'VP of Sales',
      department: 'Sales',
      birthday: null,
      notes: 'Very responsive, prefers email communication',
      avatarUrl: null,
      avatarProvider: null,
      sourceType: 'manual',
      sourceProvider: null,
      sourceId: null,
      isFavorite: false,
      isArchived: false,
      createdAt: new Date('2024-04-05'),
      updatedAt: new Date('2024-10-11'),
      lastContactedAt: new Date('2024-10-11'),
    },
    email: 'david.kumar@acme.com',
    phone: '+1-555-0234',
    tags: ['work', 'important'],
  },
  {
    contact: {
      id: '5',
      userId: '1',
      firstName: 'Lisa',
      lastName: 'Thompson',
      displayName: 'Lisa Thompson',
      nickname: 'Lisa',
      company: null,
      jobTitle: null,
      department: null,
      birthday: new Date('1992-03-08'),
      notes: 'College friend',
      avatarUrl: 'https://i.pravatar.cc/150?img=9',
      avatarProvider: null,
      sourceType: 'manual',
      sourceProvider: null,
      sourceId: null,
      isFavorite: true,
      isArchived: false,
      createdAt: new Date('2024-01-05'),
      updatedAt: new Date('2024-09-15'),
      lastContactedAt: new Date('2024-09-10'),
    },
    email: 'lisa.thompson@gmail.com',
    phone: '+1-555-0567',
    tags: ['personal', 'friends'],
  },
  {
    contact: {
      id: '6',
      userId: '1',
      firstName: 'James',
      lastName: 'Wilson',
      displayName: 'James Wilson',
      nickname: 'Jim',
      company: 'Marketing Pro',
      jobTitle: 'Marketing Manager',
      department: 'Marketing',
      birthday: null,
      notes: null,
      avatarUrl: 'https://i.pravatar.cc/150?img=14',
      avatarProvider: null,
      sourceType: 'synced',
      sourceProvider: 'microsoft',
      sourceId: 'ms_456',
      isFavorite: false,
      isArchived: false,
      createdAt: new Date('2024-05-12'),
      updatedAt: new Date('2024-10-05'),
      lastContactedAt: new Date('2024-10-02'),
    },
    email: 'james@marketingpro.com',
    phone: '+1-555-0890',
    tags: ['client'],
  },
  {
    contact: {
      id: '7',
      userId: '1',
      firstName: 'Maria',
      lastName: 'Garcia',
      displayName: 'Maria Garcia',
      nickname: null,
      company: 'Global Tech Solutions',
      jobTitle: 'Software Engineer',
      department: 'Engineering',
      birthday: new Date('1995-07-30'),
      notes: 'Open source contributor, very knowledgeable',
      avatarUrl: null,
      avatarProvider: null,
      sourceType: 'manual',
      sourceProvider: null,
      sourceId: null,
      isFavorite: false,
      isArchived: false,
      createdAt: new Date('2024-06-20'),
      updatedAt: new Date('2024-09-25'),
      lastContactedAt: new Date('2024-09-20'),
    },
    email: 'maria@globaltech.com',
    phone: null,
    tags: ['work'],
  },
  {
    contact: {
      id: '8',
      userId: '1',
      firstName: 'Robert',
      lastName: 'Anderson',
      displayName: 'Robert Anderson',
      nickname: 'Rob',
      company: 'Finance Plus',
      jobTitle: 'CFO',
      department: 'Finance',
      birthday: null,
      notes: 'Quarterly review meetings',
      avatarUrl: 'https://i.pravatar.cc/150?img=33',
      avatarProvider: null,
      sourceType: 'manual',
      sourceProvider: null,
      sourceId: null,
      isFavorite: false,
      isArchived: false,
      createdAt: new Date('2024-07-01'),
      updatedAt: new Date('2024-10-13'),
      lastContactedAt: new Date('2024-10-13'),
    },
    email: 'robert@financeplus.com',
    phone: '+1-555-0345',
    tags: ['work', 'important'],
  },
  {
    contact: {
      id: '9',
      userId: '1',
      firstName: 'Jessica',
      lastName: 'Lee',
      displayName: 'Jessica Lee',
      nickname: 'Jess',
      company: null,
      jobTitle: null,
      department: null,
      birthday: new Date('1991-12-05'),
      notes: 'Gym buddy',
      avatarUrl: 'https://i.pravatar.cc/150?img=20',
      avatarProvider: null,
      sourceType: 'manual',
      sourceProvider: null,
      sourceId: null,
      isFavorite: false,
      isArchived: false,
      createdAt: new Date('2024-03-15'),
      updatedAt: new Date('2024-08-20'),
      lastContactedAt: null,
    },
    email: 'jessica.lee@gmail.com',
    phone: '+1-555-0678',
    tags: ['personal'],
  },
  {
    contact: {
      id: '10',
      userId: '1',
      firstName: 'Thomas',
      lastName: 'Brown',
      displayName: 'Thomas Brown',
      nickname: 'Tom',
      company: 'Cloud Services Inc',
      jobTitle: 'DevOps Lead',
      department: 'Operations',
      birthday: null,
      notes: 'Expert in cloud infrastructure',
      avatarUrl: null,
      avatarProvider: null,
      sourceType: 'manual',
      sourceProvider: null,
      sourceId: null,
      isFavorite: false,
      isArchived: false,
      createdAt: new Date('2024-08-10'),
      updatedAt: new Date('2024-10-01'),
      lastContactedAt: new Date('2024-09-28'),
    },
    email: 'thomas@cloudservices.com',
    phone: '+1-555-0912',
    tags: ['work'],
  },
];

export const mockTags = [
  { id: 'work', name: 'Work', color: 'blue' },
  { id: 'personal', name: 'Personal', color: 'green' },
  { id: 'important', name: 'Important', color: 'red' },
  { id: 'client', name: 'Client', color: 'purple' },
  { id: 'startup', name: 'Startup', color: 'orange' },
  { id: 'friends', name: 'Friends', color: 'pink' },
];
